"""initial schema

Revision ID: 534a80b567ee
Revises: 
Create Date: 2026-09-14 00:19:16.592870
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UtcDateTime) are rendered fully qualified.
import app.models


revision: str = '534a80b567ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('gemini_model', sa.String(length=128), nullable=True),
    sa.Column('detector_config_version', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_source_sha256'), ['source_sha256'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('expires_at', app.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal', 'method', 'route', 'idempotency_key', name='uq_idempotency_scope')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_expires_at'), ['expires_at'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('last_seen_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('idle_expires_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('absolute_expires_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('revoked_at', app.models.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gemini_model', sa.String(length=128), nullable=True),
    sa.Column('gemini_request_cap', sa.Integer(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('key_nonce', sa.LargeBinary(length=12), nullable=True),
    sa.Column('key_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('key_tag', sa.LargeBinary(length=16), nullable=True),
    sa.Column('key_updated_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('declared_mime_type', sa.String(length=255), nullable=True),
    sa.Column('declared_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('verified_offset_bytes', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('client_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_ext', sa.String(length=16), nullable=False),
    sa.Column('probe', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_state'), ['state'], unique=False)

    op.create_table('worker_leases',
    sa.Column('lease_key', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('heartbeat_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('expires_at', app.models.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lease_key')
    )
    with op.batch_alter_table('worker_leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_leases_expires_at'), ['expires_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('target_clip_count', sa.Integer(), nullable=False),
    sa.Column('content_prompt', sa.Text(), nullable=True),
    sa.Column('content_prompt_normalized', sa.Text(), nullable=True),
    sa.Column('use_gemini', sa.Boolean(), nullable=False),
    sa.Column('gemini_model', sa.String(length=128), nullable=True),
    sa.Column('gemini_request_cap', sa.Integer(), nullable=False),
    sa.Column('detector_config_version', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('video', sa.JSON(), nullable=True),
    sa.Column('progress_phase', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(length=512), nullable=False),
    sa.Column('checkpoint', sa.String(length=32), nullable=True),
    sa.Column('eligible_count', sa.Integer(), nullable=True),
    sa.Column('detected_count', sa.Integer(), nullable=True),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('review_revision', sa.Integer(), nullable=False),
    sa.Column('partial_result_reason', sa.String(length=255), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('cache_key', sa.String(length=128), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('cleanup_completed_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_upload_id'), ['upload_id'], unique=False)

    op.create_table('analysis_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_retry', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('reserved_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('settled_at', app.models.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_attempts_job_stage', ['job_id', 'stage'], unique=False)

    op.create_table('analysis_usage',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('request_cap', sa.Integer(), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=False),
    sa.Column('coarse_requests', sa.Integer(), nullable=False),
    sa.Column('fine_requests', sa.Integer(), nullable=False),
    sa.Column('proxy_video_requests', sa.Integer(), nullable=False),
    sa.Column('proxy_video_candidates', sa.Integer(), nullable=False),
    sa.Column('provider_file_operations', sa.Integer(), nullable=False),
    sa.Column('image_bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('proxy_video_bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('proxy_video_seconds_sent', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_status', sa.String(length=16), nullable=False),
    sa.Column('local_fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('detected_shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('source_start_us', sa.BigInteger(), nullable=False),
    sa.Column('source_end_us', sa.BigInteger(), nullable=False),
    sa.Column('safe_start_us', sa.BigInteger(), nullable=False),
    sa.Column('safe_end_us', sa.BigInteger(), nullable=False),
    sa.Column('usable_duration_us', sa.BigInteger(), nullable=False),
    sa.Column('incoming_boundary', sa.JSON(), nullable=True),
    sa.Column('outgoing_boundary', sa.JSON(), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligible_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'shot_number', name='uq_detected_shots_job_number')
    )
    with op.batch_alter_table('detected_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_shots_job_id'), ['job_id'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('review_revision', sa.Integer(), nullable=False),
    sa.Column('resolutions', sa.JSON(), nullable=False),
    sa.Column('include_audio', sa.Boolean(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(length=512), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('zip_relative_path', sa.String(length=512), nullable=True),
    sa.Column('zip_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('zip_sha256', sa.String(length=64), nullable=True),
    sa.Column('manifest_available', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('completed_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exports_state'), ['state'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', app.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_job_events_job_sequence')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_job_events_job_sequence', ['job_id', 'sequence'], unique=False)

    op.create_table('provider_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('cleanup_status', sa.String(length=16), nullable=False),
    sa.Column('cleanup_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.Column('deleted_at', app.models.UtcDateTime(), nullable=True),
    sa.Column('expires_at', app.models.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_files_cleanup_status'), ['cleanup_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_files_job_id'), ['job_id'], unique=False)

    op.create_table('candidate_shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('detected_shot_id', sa.String(length=36), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('source_start_us', sa.BigInteger(), nullable=False),
    sa.Column('source_end_us', sa.BigInteger(), nullable=False),
    sa.Column('safe_start_us', sa.BigInteger(), nullable=False),
    sa.Column('safe_end_us', sa.BigInteger(), nullable=False),
    sa.Column('usable_duration_us', sa.BigInteger(), nullable=False),
    sa.Column('recommended_start_us', sa.BigInteger(), nullable=False),
    sa.Column('recommended_end_us', sa.BigInteger(), nullable=False),
    sa.Column('is_long_shot', sa.Boolean(), nullable=False),
    sa.Column('incoming_boundary', sa.JSON(), nullable=True),
    sa.Column('outgoing_boundary', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('local_score', sa.Float(), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=True),
    sa.Column('gemini_relevance', sa.Integer(), nullable=True),
    sa.Column('gemini_interest', sa.Integer(), nullable=True),
    sa.Column('gemini_clarity', sa.Integer(), nullable=True),
    sa.Column('motion_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('scoring_source', sa.String(length=32), nullable=False),
    sa.Column('cache_status', sa.String(length=16), nullable=False),
    sa.Column('prompt_relevance_evaluated', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['detected_shot_id'], ['detected_shots.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'detected_shot_id', name='uq_candidate_per_detected_shot')
    )
    with op.batch_alter_table('candidate_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_shots_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_candidate_shots_job_rank', ['job_id', 'rank'], unique=False)

    op.create_table('export_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.Column('archive_path', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('start_us', sa.BigInteger(), nullable=False),
    sa.Column('end_us', sa.BigInteger(), nullable=False),
    sa.Column('duration_us', sa.BigInteger(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('export_id', 'resolution', 'serial', name='uq_export_file_slot')
    )
    with op.batch_alter_table('export_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_files_export_id'), ['export_id'], unique=False)

    op.create_table('selected_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_us', sa.BigInteger(), nullable=False),
    sa.Column('end_us', sa.BigInteger(), nullable=False),
    sa.Column('duration_us', sa.BigInteger(), nullable=False),
    sa.Column('review_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_shots.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_selected_clip_candidate'),
    sa.UniqueConstraint('job_id', 'order_index', name='uq_selected_clip_order')
    )
    with op.batch_alter_table('selected_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selected_clips_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selected_clips_job_id'))

    op.drop_table('selected_clips')
    with op.batch_alter_table('export_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_files_export_id'))

    op.drop_table('export_files')
    with op.batch_alter_table('candidate_shots', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_shots_job_rank')
        batch_op.drop_index(batch_op.f('ix_candidate_shots_job_id'))

    op.drop_table('candidate_shots')
    with op.batch_alter_table('provider_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_files_job_id'))
        batch_op.drop_index(batch_op.f('ix_provider_files_cleanup_status'))

    op.drop_table('provider_files')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_job_events_job_sequence')

    op.drop_table('job_events')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_state'))
        batch_op.drop_index(batch_op.f('ix_exports_job_id'))

    op.drop_table('exports')
    with op.batch_alter_table('detected_shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_shots_job_id'))

    op.drop_table('detected_shots')
    op.drop_table('analysis_usage')
    with op.batch_alter_table('analysis_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_attempts_job_stage')

    op.drop_table('analysis_attempts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_upload_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_cache_key'))

    op.drop_table('jobs')
    with op.batch_alter_table('worker_leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_leases_expires_at'))

    op.drop_table('worker_leases')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_state'))
        batch_op.drop_index(batch_op.f('ix_uploads_sha256'))

    op.drop_table('uploads')
    op.drop_table('settings')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_expires_at'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_source_sha256'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
